id: P9593C452
initial_creation_type: ocr
source_metadata:
  volumes:
    118e5440e729467696e67128936bcac2:
      base_file: v056.txt
      image_group_id: I1PD95901
      title: འཕགས་པ་བཅོམ་ལྡན་འདས་མ་ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པ་རྡོ་རྗེ་གཅོད་པའི་དོན་བདུན་གྱི་རྒྱ་ཆེར་འགྲེལ་པ།
      total_pages: 1682
      volume_number: 56
